// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq1-vZT45MSeOu9XkflKAk5tpeRB25Nh0',
    appId: '1:116626303440:web:3884959d8414c9d25671d5',
    messagingSenderId: '116626303440',
    projectId: 'intgress',
    authDomain: 'intgress.firebaseapp.com',
    storageBucket: 'intgress.appspot.com',
    measurementId: 'G-N3ES20E665',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAM6srZbZ_GFTxtuQJEqWCef0Fcy4GQkI',
    appId: '1:116626303440:android:36a151c81eda46f95671d5',
    messagingSenderId: '116626303440',
    projectId: 'intgress',
    storageBucket: 'intgress.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-gIB4klJvN3POWOpAAWg76ATN_2ftsL8',
    appId: '1:116626303440:ios:8e0fb075bdd18a095671d5',
    messagingSenderId: '116626303440',
    projectId: 'intgress',
    storageBucket: 'intgress.appspot.com',
    iosBundleId: 'com.example.intgress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-gIB4klJvN3POWOpAAWg76ATN_2ftsL8',
    appId: '1:116626303440:ios:6cac7331b81348c65671d5',
    messagingSenderId: '116626303440',
    projectId: 'intgress',
    storageBucket: 'intgress.appspot.com',
    iosBundleId: 'com.example.intgress.RunnerTests',
  );
}
